# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.CharField(max_length=48, verbose_name='name [tr]')),
                ('name_en', models.CharField(max_length=48, verbose_name='name [en]')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rstorch.Category', verbose_name='parent')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'verbose_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.BigIntegerField(unique=True, verbose_name='store code')),
                ('store_name', models.CharField(max_length=48, verbose_name='store name')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='longitude')),
                ('creation_time', models.DateField(auto_now_add=True, verbose_name='creation time')),
                ('address', models.TextField(verbose_name='address')),
                ('primary_phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='primary phone number')),
                ('secondary_phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='secondary phone number')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('website_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='website address')),
                ('contact_name', models.CharField(max_length=30, verbose_name='contact name')),
                ('contact_phone_number', models.CharField(max_length=11, verbose_name='contact phone number')),
                ('contact_email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='contact email address')),
                ('hours_monday_open', models.TimeField(blank=True, null=True, verbose_name='monday opening')),
                ('hours_monday_close', models.TimeField(blank=True, null=True, verbose_name='monday closing')),
                ('hours_tuesday_open', models.TimeField(blank=True, null=True, verbose_name='tuesday opening')),
                ('hours_tuesday_close', models.TimeField(blank=True, null=True, verbose_name='tuesday closing')),
                ('hours_wednesday_open', models.TimeField(blank=True, null=True, verbose_name='wednesday opening')),
                ('hours_wednesday_close', models.TimeField(blank=True, null=True, verbose_name='wednesday closing')),
                ('hours_thursday_open', models.TimeField(blank=True, null=True, verbose_name='thursday opening')),
                ('hours_thursday_close', models.TimeField(blank=True, null=True, verbose_name='thursday closing')),
                ('hours_friday_open', models.TimeField(blank=True, null=True, verbose_name='friday opening')),
                ('hours_friday_close', models.TimeField(blank=True, null=True, verbose_name='friday closing')),
                ('hours_saturday_open', models.TimeField(blank=True, null=True, verbose_name='saturday opening')),
                ('hours_saturday_close', models.TimeField(blank=True, null=True, verbose_name='saturday closing')),
                ('hours_sunday_open', models.TimeField(blank=True, null=True, verbose_name='sunday opening')),
                ('hours_sunday_close', models.TimeField(blank=True, null=True, verbose_name='sunday closing')),
            ],
            options={
                'verbose_name_plural': 'stores',
                'verbose_name': 'store',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='stores',
            field=models.ManyToManyField(blank=True, to='rstorch.Store', verbose_name='store'),
        ),
    ]
