# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nametr', models.CharField(max_length=48)),
                ('nameen', models.CharField(max_length=48)),
                ('parent_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restfulstorch.Category')),
            ],
        ),
    ]
