# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True, verbose_name='weekday')),
                ('opening_time', models.TimeField(verbose_name='opening time')),
                ('closing_time', models.TimeField(verbose_name='closing time')),
            ],
            options={
                'verbose_name': 'business hours',
                'verbose_name_plural': 'business hours',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.CharField(max_length=48, verbose_name='name [tr]')),
                ('name_en', models.CharField(max_length=48, verbose_name='name [en]')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.BigIntegerField(unique=True, verbose_name='store code')),
                ('store_name', models.CharField(max_length=48, verbose_name='store name')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='longitude')),
                ('creation_time', models.DateField(auto_now_add=True, verbose_name='creation time')),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
            },
        ),
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='address')),
                ('primary_phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='primary phone number')),
                ('secondary_phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='secondary phone number')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('website_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='website address')),
                ('contact_name', models.CharField(max_length=30, verbose_name='contact name')),
                ('contact_phone_number', models.CharField(max_length=11, verbose_name='contact phone number')),
                ('contact_email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='contact email address')),
                ('business_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restfulstorch.BusinessHours', verbose_name='business hours')),
            ],
            options={
                'verbose_name': 'store details',
                'verbose_name_plural': 'store details',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='companies',
            field=models.ManyToManyField(blank=True, to='restfulstorch.Store', verbose_name='store'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restfulstorch.Category', verbose_name='parent category'),
        ),
    ]
