# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0002_auto_20170126_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='indexnum',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
