# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0003_auto_20170209_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='children',
        ),
        migrations.AddField(
            model_name='category',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, to='restfulstorch.Category', verbose_name='subcategory'),
        ),
    ]
