# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0003_place_indexnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='indexnum',
            field=models.BigIntegerField(unique=True),
        ),
    ]
