# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0004_auto_20170210_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='children',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restfulstorch.Category', verbose_name='subcategory'),
        ),
    ]
