# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0004_auto_20170126_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='email',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='website',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='phonenumber1',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='place',
            name='phonenumber2',
            field=models.CharField(max_length=11),
        ),
    ]
