# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0005_auto_20170126_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='phonenumber1',
            field=models.CharField(max_length=11, verbose_name='primary phone number'),
        ),
        migrations.AlterField(
            model_name='place',
            name='phonenumber2',
            field=models.CharField(blank=True, max_length=11, verbose_name='secondary phone number'),
        ),
        migrations.AlterField(
            model_name='place',
            name='website',
            field=models.CharField(max_length=128, verbose_name='website address'),
        ),
    ]
