# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0006_auto_20170215_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='details',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='details_of', to='restfulstorch.StoreDetails'),
            preserve_default=False,
        ),
    ]
