# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0006_auto_20170126_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='indexnum',
        ),
        migrations.AddField(
            model_name='place',
            name='storecode',
            field=models.BigIntegerField(default=1, unique=True, verbose_name='store code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='nameen',
            field=models.CharField(max_length=48, verbose_name='name [en]'),
        ),
        migrations.AlterField(
            model_name='category',
            name='nametr',
            field=models.CharField(max_length=48, verbose_name='name [tr]'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=500, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=48, verbose_name='store name'),
        ),
    ]
