# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0008_auto_20170126_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nameen',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nametr',
            new_name='name_tr',
        ),
        migrations.RemoveField(
            model_name='place',
            name='email',
        ),
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.RemoveField(
            model_name='place',
            name='phonenumber1',
        ),
        migrations.RemoveField(
            model_name='place',
            name='phonenumber2',
        ),
        migrations.RemoveField(
            model_name='place',
            name='storecode',
        ),
        migrations.RemoveField(
            model_name='place',
            name='website',
        ),
        migrations.AddField(
            model_name='place',
            name='email_address',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='primary_phone_number',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='place',
            name='store_code',
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='store_name',
            field=models.CharField(default=1, max_length=48),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='website_address',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
