# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0009_auto_20170126_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='contact_email_address',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='contact_phone_number',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
