# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0011_auto_20170126_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='creation_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
