# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0012_place_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sellers',
            field=models.ManyToManyField(to='restfulstorch.Place'),
        ),
    ]
