# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0014_auto_20170127_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sellers',
            field=models.ManyToManyField(blank=True, to='restfulstorch.Place'),
        ),
    ]
