# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0015_auto_20170127_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='hours_fri_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hours_fri_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hours_mon_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hours_mon_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hours_sat_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hours_sat_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hours_sun_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hours_sun_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hours_thu_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hours_thu_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hours_tue_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hours_tue_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hours_wed_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hours_wed_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='contact_email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='primary_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='website_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
