# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0017_auto_20170129_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True, verbose_name='weekday')),
                ('opening_time', models.TimeField(verbose_name='opening time')),
                ('closing_time', models.TimeField(verbose_name='closing time')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateField(auto_now_add=True, verbose_name='creation time')),
                ('store_code', models.BigIntegerField(unique=True, verbose_name='store code')),
                ('store_name', models.CharField(max_length=48, verbose_name='store name')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='longitude')),
                ('address', models.TextField(verbose_name='address')),
                ('primary_phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='primary phone number')),
                ('secondary_phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='secondary phone number')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('website_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='website address')),
                ('contact_name', models.CharField(max_length=30, verbose_name='contact name')),
                ('contact_phone_number', models.CharField(max_length=11, verbose_name='contact phone number')),
                ('contact_email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='contact email address')),
            ],
            options={
                'verbose_name': 'store',
            },
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='store',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='companies',
            field=models.ManyToManyField(blank=True, to='restfulstorch.Store', verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restfulstorch.Category', verbose_name='parent category'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
        migrations.AddField(
            model_name='businesshours',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restfulstorch.Store', verbose_name='store'),
        ),
    ]
