# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0018_auto_20170205_0421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'store', 'verbose_name_plural': 'stores'},
        ),
    ]
