# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0019_auto_20170206_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='address')),
                ('primary_phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='primary phone number')),
                ('secondary_phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='secondary phone number')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('website_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='website address')),
                ('contact_name', models.CharField(max_length=30, verbose_name='contact name')),
                ('contact_phone_number', models.CharField(max_length=11, verbose_name='contact phone number')),
                ('contact_email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='contact email address')),
            ],
            options={
                'verbose_name': 'store details',
            },
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='store',
        ),
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='contact_email_address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='contact_phone_number',
        ),
        migrations.RemoveField(
            model_name='store',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='primary_phone_number',
        ),
        migrations.RemoveField(
            model_name='store',
            name='secondary_phone_number',
        ),
        migrations.RemoveField(
            model_name='store',
            name='website_address',
        ),
        migrations.AddField(
            model_name='storedetails',
            name='business_hours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restfulstorch.BusinessHours', verbose_name='business hours'),
        ),
    ]
