# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfulstorch', '0020_auto_20170206_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesshours',
            options={'verbose_name': 'business hours', 'verbose_name_plural': 'business hours'},
        ),
        migrations.AlterModelOptions(
            name='storedetails',
            options={'verbose_name': 'store details', 'verbose_name_plural': 'store details'},
        ),
    ]
